import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");
const compactHeight = height < 720;
const contentTop = Math.min(320, Math.max(246, height * 0.37));
const shapeSize = Math.min(width * 1.28, 500);

export const COLORS = {
  background: "#FFFFFF",
  primary: "#047857",
  primaryDark: "#035F46",
  primarySoft: "#DDF8EA",
  primaryMist: "#F0FFF7",
  white: "#FFFFFF",
  text: "#111815",
  muted: "#7F8A84",
  border: "#DDE6E1",
  danger: "#B91C1C",
  placeholder: "#A5AEA9",
};

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  keyboard: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: height,
    backgroundColor: COLORS.background,
  },
  topShape: {
    position: "absolute",
    top: -shapeSize * 0.43,
    left: -shapeSize * 0.28,
    width: shapeSize,
    height: shapeSize,
    borderRadius: shapeSize / 2,
    backgroundColor: COLORS.primarySoft,
  },
  topShapeGlow: {
    position: "absolute",
    top: -shapeSize * 0.33,
    left: -shapeSize * 0.18,
    width: shapeSize * 0.72,
    height: shapeSize * 0.72,
    borderRadius: (shapeSize * 0.72) / 2,
    backgroundColor: COLORS.primaryMist,
    opacity: 0.72,
  },
  formCard: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    paddingHorizontal: width < 360 ? 26 : 34,
    paddingTop: contentTop,
    paddingBottom: compactHeight ? 30 : 44,
  },
  title: {
    color: COLORS.text,
    fontSize: compactHeight ? 30 : 33,
    lineHeight: compactHeight ? 36 : 40,
    fontWeight: "900",
    marginBottom: 10,
  },
  signupText: {
    color: COLORS.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    marginBottom: compactHeight ? 28 : 38,
  },
  signupLink: {
    color: COLORS.primary,
    fontWeight: "900",
  },
  inputShell: {
    width: "100%",
    minHeight: 58,
    borderRadius: 29,
    borderWidth: 1.2,
    borderColor: COLORS.border,
    backgroundColor: "#FFFFFF",
    paddingLeft: 17,
    paddingRight: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#0B2A1F",
    shadowOpacity: 0.045,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 1,
  },
  passwordShell: {
    marginTop: 14,
    paddingRight: 10,
  },
  inputShellFocused: {
    borderColor: COLORS.primary,
    shadowColor: COLORS.primaryDark,
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  inputField: {
    flex: 1,
    minWidth: 0,
    height: 54,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "700",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  eyeButton: {
    width: 34,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  forgotButton: {
    minHeight: 42,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  forgotText: {
    color: COLORS.primary,
    fontSize: 10,
    fontWeight: "900",
  },
  errorBox: {
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 12,
    marginTop: 16,
  },
  errorText: {
    flex: 1,
    color: COLORS.danger,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  loginButton: {
    minWidth: 132,
    minHeight: 58,
    borderRadius: 21,
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
    gap: 8,
    marginTop: compactHeight ? 34 : 54,
    paddingHorizontal: 22,
    shadowColor: COLORS.primaryDark,
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  loginButtonDisabled: {
    opacity: 0.72,
    shadowOpacity: 0,
    elevation: 0,
  },
  loginButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: "900",
  },
});